Repository snowflakedb/snowflake-cli, pull requests merged in 2024-09, with the labels that each got.

#1524 Tests cleanup for `snow ws migrate`
  src/snowflake/cli/api/project/definition_conversion.py
  tests/test_data/projects/migration_already_v2/app.py
  tests/test_data/projects/migration_already_v2/environment.yml
  tests/test_data/projects/migration_already_v2/pages/my_page.py
  tests/test_data/projects/migration_already_v2/requirements.txt
  tests/test_data/projects/migration_already_v2/snowflake.yml
  tests/test_data/projects/migration_already_v2/streamlit_app.py
  tests/test_data/projects/migration_snowpark_V2/requirements.txt
  tests/test_data/projects/migration_snowpark_v1_to_v2/app.py
  tests/test_data/projects/migration_snowpark_v1_to_v2/requirements.txt
  tests/test_data/projects/migration_snowpark_v1_to_v2/snowflake.yml
  tests/test_data/projects/migration_streamlit_V2/pages/my_page.py
  tests/test_data/projects/migration_streamlit_V2/pages/streamlit_app.py
  tests/test_data/projects/migration_streamlit_V2/snowflake.yml
  tests/test_data/projects/migration_streamlit_v1_to_v2/app.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/environment.yml
  tests/test_data/projects/migration_streamlit_v1_to_v2/pages/__init__.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/pages/my_page.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/snowflake.yml
  tests/workspace/__snapshots__/test_manager.ambr
  tests/workspace/test_manager.py
Labels: 3.0

#1533 fix diag_log_path default value
  src/snowflake/cli/api/commands/flags.py
  tests/test_connection.py
  tests/test_sql.py
Labels: 3.0

#1536 SNOW-1643030 Add Native App support to `snow ws migrate` command
  src/snowflake/cli/_plugins/snowpark/commands.py
  src/snowflake/cli/_plugins/streamlit/commands.py
  src/snowflake/cli/_plugins/workspace/commands.py
  src/snowflake/cli/api/project/definition_conversion.py
  tests/project/test_project_definition_v2.py
  tests/test_data/projects/migration_multiple_entities/app/README.md
  tests/test_data/projects/migration_multiple_entities/app/manifest.yml
  tests/test_data/projects/migration_multiple_entities/app/setup.sql
  tests/test_data/projects/migration_multiple_entities/snowflake.yml
  tests/test_data/projects/migration_multiple_entities/to_process/some_python.py
  tests/workspace/__snapshots__/test_manager.ambr
  tests/workspace/test_manager.py
Labels: 3.0

#1541 Snow 1650685 fix snowpark package
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/models.py
  tests/snowpark/test_models.py
  tests_integration/test_package.py
Labels: 3.0, 2.8.1

#1551 Update release notes after 2.8.1 release
  RELEASE-NOTES.md
Labels: 3.0

#1513 Remove defaults and fix mixins behavior
  src/snowflake/cli/api/identifiers.py
  src/snowflake/cli/api/project/schemas/entities/common.py
  src/snowflake/cli/api/project/schemas/identifier_model.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  tests/project/test_project_definition_v2.py
  tests/test_data/projects/mixins_defaults_hierarchy/snowflake.yml
  tests/test_data/projects/mixins_different_entities/snowflake.yml
  tests/test_data/projects/mixins_list_applied_in_order/snowflake.yml
  tests_integration/spcs/test_registry.py
  tests_integration/test_data/projects/project_definition_v2/snowflake.yml
  tests_integration/test_data/projects/snowpark_v2/snowflake.yml
Labels: 3.0

#1568 Add override tag support in mixins
  src/snowflake/cli/api/project/definition.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  src/snowflake/cli/api/utils/definition_rendering.py
  tests/api/utils/test_override_tag.py
Labels: 3.0

#1584 Remove use of DictCursor for use_role
  src/snowflake/cli/api/sql_execution.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_project_model.py
  tests/nativeapp/test_run_processor.py
  tests/nativeapp/test_teardown_processor.py
  tests/nativeapp/test_version_create_processor.py
  tests/nativeapp/test_version_drop_processor.py
  tests/stage/test_stage.py
  tests/workspace/test_application_package_entity.py
Labels: 3.0

#1583 Fix negative execution time
  src/snowflake/cli/api/commands/snow_typer.py
  tests/api/commands/test_snow_typer.py
Labels: 3.0

#1588 Remove DictCursor from use_warehouse
  src/snowflake/cli/api/sql_execution.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_package_scripts.py
  tests/nativeapp/test_run_processor.py
Labels: 3.0

#1590 Add imports support in Streamlit
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/snowpark_entity_model.py
  src/snowflake/cli/_plugins/streamlit/manager.py
  src/snowflake/cli/_plugins/streamlit/streamlit_entity_model.py
  src/snowflake/cli/api/project/schemas/entities/common.py
  tests/streamlit/test_streamlit_manager.py
  tests_integration/test_streamlit.py
Labels: 3.0

#1589 Remove owner check in native app logic
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/application_entity.py
  src/snowflake/cli/_plugins/nativeapp/application_package_entity.py
  src/snowflake/cli/_plugins/nativeapp/exceptions.py
  src/snowflake/cli/_plugins/nativeapp/same_account_install_method.py
  src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
  src/snowflake/cli/api/entities/utils.py
  src/snowflake/cli/api/errno.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_run_processor.py
  tests/nativeapp/test_teardown_processor.py
  tests/nativeapp/utils.py
Labels: 3.0

#1596 Fix incorrect test assertions
  tests/nativeapp/test_teardown_processor.py
Labels: 3.0

#1557 SNOW-1653909 If we can't find an app entity to convert, only fail if it's required, update `snow app teardown` to tear down multiple apps
  src/snowflake/cli/_plugins/nativeapp/commands.py
  src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
  src/snowflake/cli/_plugins/nativeapp/version/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/nativeapp/test_v2_to_v1.py
  tests/test_data/projects/integration_templated_v2/snowflake.yml
  tests/test_data/projects/integration_v2/snowflake.yml
  tests_integration/nativeapp/conftest.py
  tests_integration/nativeapp/test_init_run.py
  tests_integration/nativeapp/test_teardown.py
Labels: 3.0

#1602 Fix numerical version when reading from manifest file
  src/snowflake/cli/_plugins/nativeapp/artifacts.py
  src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
  tests/nativeapp/test_artifacts.py
  tests_integration/nativeapp/test_version.py
Labels: 3.0

#1598 Rename ws migrate to migrate-definition
  RELEASE-NOTES.md
  src/snowflake/cli/_app/commands_registration/builtin_plugins.py
  src/snowflake/cli/_plugins/helpers/__init__.py
  src/snowflake/cli/_plugins/helpers/commands.py
  src/snowflake/cli/_plugins/helpers/plugin_spec.py
  src/snowflake/cli/_plugins/workspace/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/helpers/__init__.py
  tests/helpers/__snapshots__/test_v1_to_v2.ambr
  tests/helpers/test_v1_to_v2.py
  tests/test_help_messages.py
  tests/workspace/test_manager.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: 3.0

#1605 Bring back glob support in streamlit
  src/snowflake/cli/_plugins/streamlit/streamlit_entity_model.py
  tests/streamlit/__snapshots__/test_commands.ambr
  tests/streamlit/test_commands.py
  tests_integration/test_streamlit.py
Labels: 3.0

#1600 Catch error on deploy for package with special comment
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/application_entity.py
  src/snowflake/cli/_plugins/nativeapp/application_package_entity.py
  src/snowflake/cli/_plugins/nativeapp/commands.py
  src/snowflake/cli/_plugins/nativeapp/manager.py
  src/snowflake/cli/_plugins/nativeapp/policy.py
  src/snowflake/cli/_plugins/nativeapp/run_processor.py
  src/snowflake/cli/_plugins/workspace/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/nativeapp/test_manager.py
  tests/workspace/test_application_package_entity.py
  tests_integration/nativeapp/test_deploy.py
Labels: 3.0

#1606 Don't error on a PDFv2 with multiple entities if it's not required
  src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
  tests/nativeapp/test_v2_to_v1.py
Labels: 3.0

#1629 Don't sort keys when converting PDFv1 to v2
  src/snowflake/cli/_plugins/helpers/commands.py
  tests/helpers/__snapshots__/test_v1_to_v2.ambr
Labels: 3.0.1

#1630 Remove `snow app init` command
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/commands.py
  src/snowflake/cli/_plugins/nativeapp/init.py
  tests/__snapshots__/test_help_messages.ambr
  tests/nativeapp/test_commands.py
  tests/nativeapp/test_init.py
  tests_integration/nativeapp/__snapshots__/test_deploy.ambr
  tests_integration/nativeapp/test_init_run.py
  tests_integration/nativeapp/test_templates.py
Labels: 3.0

#1632 Don't output default native_app fields in v1 to v2 migration
  src/snowflake/cli/_plugins/helpers/commands.py
  src/snowflake/cli/api/project/definition_conversion.py
  tests/helpers/__snapshots__/test_v1_to_v2.ambr
  tests/helpers/test_v1_to_v2.py
  tests/test_data/projects/migration_all_app_entities/__init__.py
  tests/test_data/projects/migration_all_app_entities/app.py
  tests/test_data/projects/migration_all_app_entities/app/README.md
  tests/test_data/projects/migration_all_app_entities/app/manifest.yml
  tests/test_data/projects/migration_all_app_entities/app/setup.sql
  tests/test_data/projects/migration_all_app_entities/scripts/post_app_deploy.sql
  tests/test_data/projects/migration_all_app_entities/scripts/post_pkg_deploy.sql
  tests/test_data/projects/migration_all_app_entities/snowflake.yml
  tests/test_data/projects/migration_all_app_entities/to_process/some_python.py
  tests/test_data/projects/migration_multiple_entities/snowflake.yml
Labels: 3.0

#1637 Find deeply-nested manifest.yml when converting v1 to v2
  src/snowflake/cli/api/project/definition_conversion.py
  tests/helpers/test_v1_to_v2.py
Labels: 3.0
