Repository snowflakedb/snowflake-cli, pull requests merged in 2024-07, with the labels that each got.

#1277 Improve message for Pydantic model errors and move exception translation up to fix Pydantic Union issue.
  RELEASE-NOTES.md
  src/snowflake/cli/api/project/errors.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  src/snowflake/cli/api/project/schemas/updatable_model.py
  src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
  tests/nativeapp/test_post_deploy.py
  tests/project/test_config.py
Labels: 2.6.0

#1278 show create command
  src/snowflake/cli/plugins/object/commands.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.6.0

#1279 Add warning when templating is used in v1
  RELEASE-NOTES.md
  src/snowflake/cli/api/utils/definition_rendering.py
  tests/api/utils/test_definition_rendering.py
Labels: 2.6.0

#1302 Adjust examples for object type argument
  src/snowflake/cli/plugins/object/commands.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.6.0

#1018 Add support for "execute immediate" for python files
  .github/workflows/test_integration.yaml
  .gitignore
  RELEASE-NOTES.md
  pyproject.toml
  snyk/requirements.txt
  src/snowflake/cli/api/commands/flags.py
  src/snowflake/cli/api/identifiers.py
  src/snowflake/cli/api/sql_execution.py
  src/snowflake/cli/plugins/cortex/commands.py
  src/snowflake/cli/plugins/snowpark/models.py
  src/snowflake/cli/plugins/stage/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/stage/__snapshots__/test_stage.ambr
  tests/stage/test_stage.py
  tests_integration/__snapshots__/test_stage.ambr
  tests_integration/test_data/projects/stage_execute/requirements.txt
  tests_integration/test_data/projects/stage_execute/script1.py
  tests_integration/test_data/projects/stage_execute/script_template.py
  tests_integration/test_snowpark.py
  tests_integration/test_stage.py
Labels: enhancement

#1306 Missing log directory when disabled save logs fix
  src/snowflake/cli/api/config.py
  src/snowflake/cli/app/cli_app.py
  src/snowflake/cli/app/loggers.py
  tests/test_config.py
  tests/test_logs.py
Labels: 2.6.1

#1315 Snow 1533042 create error handling fix
  RELEASE-NOTES.md
  src/snowflake/cli/api/rest_api.py
  src/snowflake/cli/plugins/object/manager.py
  tests/api/test_rest_api.py
  tests_integration/test_object.py
Labels: 2.6.1

#1317 Added fix with logs to release notes
  RELEASE-NOTES.md
Labels: 2.6.1

#1368 Add spaces in deprecated init help messages
  src/snowflake/cli/api/commands/project_initialisation.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.7.0

#1014 Drop support for Python <3.10
  .github/workflows/matrix.yaml
  CONTRIBUTING.md
  README.md
  RELEASE-NOTES.md
  pyproject.toml
Labels: 3.X, future-bcr

#1373 Remove object stage command group
  RELEASE-NOTES.md
  src/snowflake/cli/app/commands_registration/builtin_plugins.py
  src/snowflake/cli/plugins/object_stage_deprecated/__init__.py
  src/snowflake/cli/plugins/object_stage_deprecated/commands.py
  src/snowflake/cli/plugins/object_stage_deprecated/plugin_spec.py
  tests/__snapshots__/test_help_messages.ambr
  tests/object/test_stage.py
  tests/stage/test_diff.py
Labels: 3.X, future-bcr

#1395 Added --token-file-path for connection add command
  src/snowflake/cli/api/config.py
  src/snowflake/cli/plugins/connection/commands.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.7.0
