Repository snowflakedb/snowflake-cli, pull requests merged in 2024-02, with the labels that each got.

#808 Fix for integration tests
  tests_integration/test_snowpark.py
Labels: bug fix

#795 Snow 978274 add database and schema to project definition
  RELEASE-NOTES.md
  src/snowflake/cli/api/project/schemas/snowpark.py
  src/snowflake/cli/api/sql_execution.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/common.py
  tests/snowpark/__snapshots__/test_function.ambr
  tests/snowpark/__snapshots__/test_procedure.ambr
  tests/snowpark/test_function.py
  tests/snowpark/test_procedure.py
  tests/test_data/projects/snowpark_function_fully_qualified_name/app.zip
  tests/test_data/projects/snowpark_function_fully_qualified_name/app/app.py
  tests/test_data/projects/snowpark_function_fully_qualified_name/requirements.txt
  tests/test_data/projects/snowpark_function_fully_qualified_name/snowflake.yml
  tests/test_data/projects/snowpark_procedure_fully_qualified_name/app.zip
  tests/test_data/projects/snowpark_procedure_fully_qualified_name/app/app.py
  tests/test_data/projects/snowpark_procedure_fully_qualified_name/requirements.txt
  tests/test_data/projects/snowpark_procedure_fully_qualified_name/snowflake.yml
  tests/testing_utils/fixtures.py
  tests_integration/conftest.py
  tests_integration/test_data/projects/snowpark_fully_qualified_name/.gitignore
  tests_integration/test_data/projects/snowpark_fully_qualified_name/app/app.py
  tests_integration/test_data/projects/snowpark_fully_qualified_name/requirements.txt
  tests_integration/test_data/projects/snowpark_fully_qualified_name/snowflake.yml
  tests_integration/test_snowpark.py
  tests_integration/test_snowpark_external_access.py
Labels: RELEASE

#804 Fix for password warning shown twice
  src/snowflake/cli/plugins/connection/commands.py
  tests/test_connection.py
Labels: bug fix

#809 Reduce 'swnowcli' usage and hide plugins flag
  src/snowflake/cli/app/cli_app.py
  tests/test_cli.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: RELEASE

#801 Test and fix initialization of a NA project from a repo with a single template
  src/snowflake/cli/plugins/nativeapp/init.py
  tests/nativeapp/test_init.py
  tests_integration/test_nativeapp.py
Labels: RELEASE

#812 Add session context validation in connection test
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/connection/commands.py
  tests/app/test_telemetry.py
  tests/test_connection.py
Labels: RELEASE

#805 SNOW-1055803: Adding compute-pool status command
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/spcs/compute_pool/commands.py
  src/snowflake/cli/plugins/spcs/compute_pool/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/spcs/test_compute_pool.py
  tests_integration/spcs/testing_utils/compute_pool_utils.py
Labels: RELEASE

#820 Updated help messages
  src/snowflake/cli/plugins/connection/commands.py
  src/snowflake/cli/plugins/nativeapp/commands.py
  src/snowflake/cli/plugins/nativeapp/version/commands.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/snowpark_shared.py
  src/snowflake/cli/plugins/spcs/compute_pool/commands.py
  src/snowflake/cli/plugins/spcs/jobs/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/test_cli.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: RELEASE

#819 SNOW-1057322: Adding support for qualified names for services.
  RELEASE-NOTES.md
  src/snowflake/cli/api/project/util.py
  src/snowflake/cli/plugins/spcs/compute_pool/commands.py
  src/snowflake/cli/plugins/spcs/image_repository/commands.py
  src/snowflake/cli/plugins/spcs/services/commands.py
  src/snowflake/cli/plugins/spcs/services/manager.py
  tests/project/test_util.py
  tests/spcs/test_services.py
Labels: RELEASE

#839 Snow 1105625 git list branches tags
  src/snowflake/cli/plugins/git/commands.py
  src/snowflake/cli/plugins/git/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/git/test_git_commands.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: Do not merge

#841 Snow 1105565 snow git fetch and list-files
  src/snowflake/cli/plugins/git/commands.py
  src/snowflake/cli/plugins/git/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/git/test_git_commands.py
Labels: Do not merge

#844 [NADE] PMM Updates to NA Commands
  src/snowflake/cli/api/commands/flags.py
  src/snowflake/cli/plugins/nativeapp/artifacts.py
  src/snowflake/cli/plugins/nativeapp/commands.py
  src/snowflake/cli/plugins/nativeapp/constants.py
  src/snowflake/cli/plugins/nativeapp/exceptions.py
  src/snowflake/cli/plugins/nativeapp/init.py
  src/snowflake/cli/plugins/nativeapp/manager.py
  src/snowflake/cli/plugins/nativeapp/run_processor.py
  src/snowflake/cli/plugins/nativeapp/teardown_processor.py
  src/snowflake/cli/plugins/nativeapp/version/commands.py
  src/snowflake/cli/plugins/nativeapp/version/version_processor.py
  tests/__snapshots__/test_help_messages.ambr
  tests/nativeapp/__snapshots__/test_commands.ambr
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_run_processor.py
  tests/nativeapp/test_teardown_processor.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: RELEASE
