Repository snowflakedb/snowflake-cli, pull requests merged in 2024-03, with the labels that each got.

#853 Remove external access from snowpark template
  src/snowflake/cli/templates/default_snowpark/app/procedures.py
  src/snowflake/cli/templates/default_snowpark/snowflake.yml
Labels: RELEASE

#849 Capitalization fix
  src/snowflake/cli/plugins/nativeapp/manager.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/common.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package/utils.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  src/snowflake/cli/plugins/streamlit/streamlit_utils.py
  tests/__snapshots__/test_help_messages.ambr
  tests/snowpark/__snapshots__/test_package.ambr
Labels: RELEASE

#781 Fixes for package creation and pip installs
  .pre-commit-config.yaml
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/snowpark/models.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package/manager.py
  src/snowflake/cli/plugins/snowpark/package/utils.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  src/snowflake/cli/plugins/snowpark/snowpark_shared.py
  src/snowflake/cli/plugins/snowpark/venv.py
  tests/__snapshots__/test_help_messages.ambr
  tests/snowpark/test_models.py
  tests/snowpark/test_package.py
  tests/snowpark/test_snowpark_shared.py
  tests/test_data/test_data.py
  tests/test_utils.py
  tests_integration/test_package.py
  tests_integration/test_snowpark.py
  tests_integration/test_streamlit.py
  tests_integration/testing_utils/snowpark_utils.py
Labels: bug

#898 Remove StrictYaml from project
  .snyk/req-auto-generated.txt
  pyproject.toml
  src/snowflake/cli/plugins/spcs/services/manager.py
  tests/spcs/test_services.py
  tests_integration/conftest.py
Labels: RELEASE

#909 [SNOW-1246922] Fix printing of env variables in connection list
  RELEASE-NOTES.md
  src/snowflake/cli/api/config.py
  src/snowflake/cli/app/snow_connector.py
  src/snowflake/cli/plugins/connection/commands.py
  tests/test_config.py
  tests/test_connection.py
  tests/test_data/projects/snowpark_procedures/app.py
  tests/test_data/projects/snowpark_procedures_coverage/app.py
  tests_integration/test_data/projects/snowpark/app/app.py
  tests_integration/test_data/projects/snowpark_coverage/app/module/procedures.py
  tests_integration/test_data/projects/snowpark_fully_qualified_name/app/app.py
Labels: 2.1.1

#939 Add pip as requirement for snowflake cli
  pyproject.toml
  snyk/requirements.txt
Labels: 2.1.2

#947 Snow 1051580 support package create from all sources
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  src/snowflake/cli/plugins/snowpark/venv.py
  tests/snowpark/test_package.py
  tests_integration/test_package.py
Labels: 2.2.0, 2.1.3
