Repository snowflakedb/snowflake-cli, pull requests merged in 2024-08, with the labels that each got.

#1403 Moved fix for large files uploaded to AWS S3 to 2.7.0 version
  RELEASE-NOTES.md
Labels: 2.7.0

#1399 Add package post-deploy scripts in project definition file
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/manager.py
  src/snowflake/cli/_plugins/nativeapp/project_model.py
  src/snowflake/cli/_plugins/nativeapp/run_processor.py
  src/snowflake/cli/_plugins/nativeapp/v2_conversions/v2_to_v1_decorator.py
  src/snowflake/cli/_plugins/nativeapp/version/version_processor.py
  src/snowflake/cli/api/project/schemas/entities/common.py
  src/snowflake/cli/api/project/schemas/native_app/application.py
  src/snowflake/cli/api/project/schemas/native_app/package.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_post_deploy_for_app.py
  tests/nativeapp/test_post_deploy_for_package.py
  tests/nativeapp/test_v2_to_v1.py
  tests/nativeapp/test_version_create_processor.py
  tests/nativeapp/utils.py
  tests/project/__snapshots__/test_config.ambr
  tests/test_data/projects/integration_external_v2/package/001-shared.sql
  tests/test_data/projects/integration_external_v2/package/002-shared.sql
  tests/test_data/projects/integration_templated_v2/package/001-shared.sql
  tests/test_data/projects/integration_templated_v2/package/002-shared.sql
  tests/test_data/projects/integration_v2/package/001-shared.sql
  tests/test_data/projects/integration_v2/package/002-shared.sql
  tests/test_data/projects/napp_post_deploy/scripts/app_post_deploy1.sql
  tests/test_data/projects/napp_post_deploy/scripts/app_post_deploy2.sql
  tests/test_data/projects/napp_post_deploy/scripts/package_post_deploy1.sql
  tests/test_data/projects/napp_post_deploy/scripts/package_post_deploy2.sql
  tests/test_data/projects/napp_post_deploy/snowflake.yml
  tests/test_data/projects/napp_post_deploy_missing_file/snowflake.yml
  tests_integration/nativeapp/test_init_run.py
  tests_integration/nativeapp/test_post_deploy.py
  tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/app_post_deploy1.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/app_post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/package_post_deploy1.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/package_post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v1/scripts/post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v1/snowflake.yml
  tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/app_post_deploy1.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/app_post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/package_post_deploy1.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/package_post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v2/scripts/post_deploy2.sql
  tests_integration/test_data/projects/napp_application_post_deploy_v2/snowflake.yml
Labels: 2.X

#1447 Rename clean_id to sanitize_id and limit functionality. Also rename id_concat to concat_ids
  RELEASE-NOTES.md
  src/snowflake/cli/api/project/definition.py
  src/snowflake/cli/api/project/schemas/native_app/application.py
  src/snowflake/cli/api/project/schemas/native_app/package.py
  src/snowflake/cli/api/project/util.py
  src/snowflake/cli/api/utils/definition_rendering.py
  src/snowflake/cli/api/utils/templating_functions.py
  tests/api/utils/test_templating_functions.py
  tests/project/test_config.py
  tests/project/test_util.py
Labels: 3.X, 2.X

#1451 Tweak default detection to ignore transformations
  src/snowflake/cli/api/utils/definition_rendering.py
  tests/api/utils/test_definition_rendering.py
Labels: 3.X, 2.X

#1456 Snow 1633381 add jinja blocks to snow init
  src/snowflake/cli/_plugins/init/commands.py
  src/snowflake/cli/api/rendering/project_templates.py
  tests/test_data/projects/project_templating_jinja_blocks/blocks.txt
  tests/test_data/projects/project_templating_jinja_blocks/template.yml
  tests/test_init.py
Labels: 2.X

#1457 Fix snowpark aliases
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/commands.py
  tests_integration/test_snowpark.py
Labels: 2.X

#1462 Print warnings on CREATE or UPGRADE
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/run_processor.py
  tests/nativeapp/test_run_processor.py
Labels: 2.X

#1484 Add mixins
  src/snowflake/cli/api/project/schemas/entities/common.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  tests/project/test_project_definition_v2.py
  tests/test_data/projects/mixins_basic/snowflake.yml
  tests/test_data/projects/mixins_defaults_hierarchy/snowflake.yml
  tests/test_data/projects/mixins_different_entities/environment.yml
  tests/test_data/projects/mixins_different_entities/pages/my_page.py
  tests/test_data/projects/mixins_different_entities/snowflake.yml
  tests/test_data/projects/mixins_different_entities/streamlit_app.py
  tests/test_data/projects/mixins_list_applied_in_order/environment.yml
  tests/test_data/projects/mixins_list_applied_in_order/pages/my_page.py
  tests/test_data/projects/mixins_list_applied_in_order/snowflake.yml
  tests/test_data/projects/mixins_list_applied_in_order/streamlit_app.py
Labels: 3.X

#1458 Snow 1625040 unify sql template syntax
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/manager.py
  src/snowflake/cli/api/rendering/jinja.py
  src/snowflake/cli/api/rendering/sql_templates.py
  tests/test_sql.py
  tests_integration/test_sql_templating.py
Labels: 3.X

#1487 Fix integer indices in error reporting
  src/snowflake/cli/api/project/errors.py
Labels: 3.X

#1474 Added `snow ws migrate` command
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/commands.py
  src/snowflake/cli/_plugins/streamlit/commands.py
  src/snowflake/cli/_plugins/workspace/commands.py
  src/snowflake/cli/api/project/definition.py
  src/snowflake/cli/api/project/definition_manager.py
  src/snowflake/cli/api/secure_path.py
  src/snowflake/cli/api/utils/definition_rendering.py
  tests/__snapshots__/test_help_messages.ambr
  tests/project/__snapshots__/test_config.ambr
  tests/project/test_project_definition_v2.py
  tests/test_data/projects/migration_snowpark_V1_to_V2/app.py
  tests/test_data/projects/migration_snowpark_V1_to_V2/requirements.txt
  tests/test_data/projects/migration_snowpark_V1_to_V2/snowflake.yml
  tests/test_data/projects/migration_snowpark_V2/app.py
  tests/test_data/projects/migration_snowpark_V2/requirements.txt
  tests/test_data/projects/migration_snowpark_V2/snowflake.yml
  tests/test_data/projects/migration_streamlit_V1_to_V2/environment.yml
  tests/test_data/projects/migration_streamlit_V1_to_V2/pages/my_page.py
  tests/test_data/projects/migration_streamlit_V1_to_V2/snowflake.yml
  tests/test_data/projects/migration_streamlit_V1_to_V2/streamlit_app.py
  tests/test_data/projects/migration_streamlit_V2/environment.yml
  tests/test_data/projects/migration_streamlit_V2/pages/my_page.py
  tests/test_data/projects/migration_streamlit_V2/snowflake.yml
  tests/test_data/projects/migration_streamlit_V2/streamlit_app.py
  tests/test_data/projects/snowpark_templated_v1/requirements.txt
  tests/test_data/projects/snowpark_templated_v1/snowflake.yml
  tests/test_data/projects/streamlit_templated_v1/common/hello.py
  tests/test_data/projects/streamlit_templated_v1/environment.yml
  tests/test_data/projects/streamlit_templated_v1/pages/my_page.py
  tests/test_data/projects/streamlit_templated_v1/snowflake.yml
  tests/test_data/projects/streamlit_templated_v1/streamlit_app.py
  tests/workspace/__snapshots__/test_manager.ambr
  tests/workspace/test_manager.py
  tests_e2e/__snapshots__/test_installation.ambr
Labels: 3.X

#1489 Snow 1639660 cleanup "todo in 3.0" comments
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/package/anaconda_packages.py
  src/snowflake/cli/api/feature_flags.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  tests/app/test_telemetry.py
  tests/nativeapp/test_v2_to_v1.py
  tests/project/test_config.py
  tests/project/test_project_definition_v2.py
  tests/snowpark/test_anaconda.py
  tests/streamlit/conftest.py
  tests_integration/conftest.py
  tests_integration/nativeapp/test_bundle.py
  tests_integration/nativeapp/test_debug_mode.py
  tests_integration/nativeapp/test_deploy.py
  tests_integration/nativeapp/test_events.py
  tests_integration/nativeapp/test_init_run.py
  tests_integration/nativeapp/test_large_upload.py
  tests_integration/nativeapp/test_open.py
  tests_integration/nativeapp/test_post_deploy.py
  tests_integration/nativeapp/test_project_templating.py
  tests_integration/nativeapp/test_teardown.py
  tests_integration/nativeapp/test_validate.py
  tests_integration/nativeapp/test_version.py
  tests_integration/test_snowpark.py
  tests_integration/test_snowpark_external_access.py
  tests_integration/test_utils.py
  tests_integration/testing_utils/snowpark_utils.py
  tests_integration/workspaces/test_validate_schema.py
Labels: 3.X

#1450 Add Windows permissions check
  src/snowflake/cli/api/config.py
  src/snowflake/cli/api/exceptions.py
  src/snowflake/cli/api/secure_path.py
  src/snowflake/cli/api/secure_utils.py
  tests/api/test_secure_path.py
  tests/test_config.py
  tests_e2e/config/config.toml
  tests_e2e/conftest.py
  tests_e2e/test_error_handling.py
Labels: 3.0

#1515 Fixes to `snow ws migrate`
  src/snowflake/cli/_plugins/snowpark/commands.py
  src/snowflake/cli/_plugins/snowpark/common.py
  src/snowflake/cli/_plugins/streamlit/commands.py
  src/snowflake/cli/_plugins/workspace/commands.py
  src/snowflake/cli/api/constants.py
  src/snowflake/cli/api/project/definition_conversion.py
  tests/project/test_project_definition_v2.py
  tests/snowpark/test_procedure.py
  tests/test_data/projects/__init__.py
  tests/test_data/projects/migration_multiple_entities/__init__.py
  tests/test_data/projects/migration_multiple_entities/app.py
  tests/test_data/projects/migration_multiple_entities/environment.yml
  tests/test_data/projects/migration_multiple_entities/pages/__init__.py
  tests/test_data/projects/migration_multiple_entities/pages/my_page.py
  tests/test_data/projects/migration_multiple_entities/snowflake.yml
  tests/test_data/projects/migration_multiple_entities/streamlit_app.py
  tests/test_data/projects/migration_snowpark_v1_to_v2/app.py
  tests/test_data/projects/migration_snowpark_v1_to_v2/requirements.txt
  tests/test_data/projects/migration_snowpark_v1_to_v2/snowflake.yml
  tests/test_data/projects/migration_streamlit_V2/pages/streamlit_app.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/__init__.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/app.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/environment.yml
  tests/test_data/projects/migration_streamlit_v1_to_v2/pages/__init__.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/pages/my_page.py
  tests/test_data/projects/migration_streamlit_v1_to_v2/snowflake.yml
  tests/test_data/projects/migration_streamlit_v1_to_v2/streamlit_app.py
  tests/workspace/__snapshots__/test_manager.ambr
  tests/workspace/test_manager.py
Labels: 3.0
