Repository snowflakedb/snowflake-cli, pull requests merged in 2024-05, with the labels that each got.

#1023 Added support for FQN in stage and git execute
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/git/manager.py
  src/snowflake/cli/plugins/snowpark/package/manager.py
  src/snowflake/cli/plugins/stage/manager.py
  tests/git/__snapshots__/test_git_commands.ambr
  tests/git/test_git_commands.py
  tests/stage/__snapshots__/test_stage.ambr
  tests/stage/test_stage.py
  tests_integration/__snapshots__/test_git.ambr
  tests_integration/__snapshots__/test_stage.ambr
  tests_integration/test_git.py
  tests_integration/test_stage.py
Labels: 2.3.0

#1045 [SNOW-1345064] Fix stage path handling on Windows
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/nativeapp/commands.py
  src/snowflake/cli/plugins/nativeapp/manager.py
  src/snowflake/cli/plugins/stage/commands.py
  src/snowflake/cli/plugins/stage/diff.py
  tests/__snapshots__/test_help_messages.ambr
  tests/nativeapp/test_manager.py
  tests/stage/test_diff.py
  tests_integration/test_nativeapp.py
Labels: 2.3.0

#1042 Add feature flags usage to info and telemetry
  RELEASE-NOTES.md
  src/snowflake/cli/api/config.py
  src/snowflake/cli/api/utils/types.py
  src/snowflake/cli/app/cli_app.py
  src/snowflake/cli/app/telemetry.py
  tests/app/test_telemetry.py
  tests/git/__snapshots__/test_git_commands.ambr
  tests/test.toml
  tests/test_main.py
Labels: 2.3.0

#1054 Rename --data to --variables in snow sql
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/sql/commands.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.3.0

#1061 Add external access integrations to snow object commands
  RELEASE-NOTES.md
  src/snowflake/cli/api/constants.py
  tests/__snapshots__/test_help_messages.ambr
  tests_integration/test_object.py
Labels: 2.3.1, 2.4.0

#1067 Snow 1272319 alias snowcli core object commands
  RELEASE-NOTES.md
  src/snowflake/cli/api/commands/flags.py
  src/snowflake/cli/app/commands_registration/builtin_plugins.py
  src/snowflake/cli/plugins/git/commands.py
  src/snowflake/cli/plugins/object/command_aliases.py
  src/snowflake/cli/plugins/object/commands.py
  src/snowflake/cli/plugins/object_stage_deprecated/__init__.py
  src/snowflake/cli/plugins/object_stage_deprecated/commands.py
  src/snowflake/cli/plugins/object_stage_deprecated/plugin_spec.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/stage/commands.py
  src/snowflake/cli/plugins/streamlit/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/git/test_git_commands.py
  tests/snowpark/test_function.py
  tests/snowpark/test_procedure.py
  tests/stage/test_stage.py
  tests/streamlit/test_commands.py
  tests_integration/test_stage.py
  tests_integration/test_streamlit.py
Labels: future-bcr, 2.4.0

#1079 Fix creation of the 3rd+ patch on an app pkg version
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/nativeapp/constants.py
  src/snowflake/cli/plugins/nativeapp/run_processor.py
  tests/nativeapp/test_run_processor.py
  tests_integration/nativeapp/test_version.py
Labels: 2.3.1

#1078 Snow 1304163 notebook create command
  src/snowflake/cli/plugins/notebook/commands.py
  src/snowflake/cli/plugins/notebook/exceptions.py
  src/snowflake/cli/plugins/notebook/manager.py
  src/snowflake/cli/plugins/notebook/types.py
  tests/__snapshots__/test_help_messages.ambr
  tests/notebook/test_notebook_commands.py
  tests/notebook/test_notebook_manager.py
  tests_integration/notebook/__init__.py
  tests_integration/notebook/test_notebooks.py
  tests_integration/snowflake_connector.py
  tests_integration/test_data/notebook/my_notebook.ipynb
Labels: enhancement

#1101 Cortex LLM commands implementation
  RELEASE-NOTES.md
  src/snowflake/cli/api/commands/flags.py
  src/snowflake/cli/app/commands_registration/builtin_plugins.py
  src/snowflake/cli/plugins/cortex/commands.py
  src/snowflake/cli/plugins/cortex/constants.py
  src/snowflake/cli/plugins/cortex/manager.py
  src/snowflake/cli/plugins/cortex/types.py
  tests/__snapshots__/test_help_messages.ambr
  tests/cortex/test_cortex_commands.py
  tests/test_data/cortex/conversation.json
  tests/test_data/cortex/short_english_text.txt
  tests/testing_utils/result_assertions.py
  tests_e2e/__snapshots__/test_installation.ambr
  tests_integration/conftest.py
  tests_integration/test_cortex.py
  tests_integration/test_data/cortex/conversation.json
  tests_integration/test_data/cortex/english_text.txt
  tests_integration/testing_utils/assertions/test_result_assertions.py
Labels: 2.4.0

#1107 Fix default interactive flag
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/nativeapp/commands.py
  src/snowflake/cli/plugins/nativeapp/common_flags.py
  src/snowflake/cli/plugins/nativeapp/version/commands.py
  tests/__snapshots__/test_help_messages.ambr
Labels: 2.4.0

#1105 Fix application info in connection
  src/snowflake/cli/app/snow_connector.py
  tests/test_connection.py
  tests/test_main.py
  tests/test_snow_connector.py
  tests_e2e/__snapshots__/test_installation.ambr
  tests_e2e/test_installation.py
  tests_integration/__snapshots__/test_sql.ambr
  tests_integration/test_data/sql_multi_queries.sql
  tests_integration/test_sql.py
Labels: 2.4.0

#1106 Validate project definition file using proper version schema
  src/snowflake/cli/api/project/errors.py
  src/snowflake/cli/api/project/schemas/project_definition.py
  tests/project/test_config.py
  tests/project/test_project_schemas.py
Labels: 2.4.0

#1114 Handle missing snowflake-snowpark-python package dependency
  src/snowflake/cli/plugins/nativeapp/codegen/snowpark/callback_source.py.jinja
  src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
  tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr
  tests/nativeapp/codegen/snowpark/test_python_processor.py
Labels: 2.4.0

#1125 Clean up phase state on exception
  src/snowflake/cli/api/console/console.py
  tests/api/console/test_cli_console_output.py
Labels: 2.4.0

#1124 Clean up output of the setup script generation step
  src/snowflake/cli/plugins/nativeapp/codegen/compiler.py
  src/snowflake/cli/plugins/nativeapp/codegen/snowpark/python_processor.py
  tests/nativeapp/codegen/snowpark/__snapshots__/test_python_processor.ambr
  tests/nativeapp/codegen/snowpark/test_python_processor.py
Labels: 2.4.0
