Repository snowflakedb/snowflake-cli, pull requests merged in 2024-04, with the labels that each got.

#937 Snow 1260461 refactor snowpark build
  RELEASE-NOTES.md
  src/snowflake/cli/api/constants.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/models.py
  src/snowflake/cli/plugins/snowpark/package/anaconda.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package/manager.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  src/snowflake/cli/plugins/snowpark/snowpark_package_paths.py
  src/snowflake/cli/plugins/snowpark/snowpark_shared.py
  tests/__snapshots__/test_help_messages.ambr
  tests/snowpark/__snapshots__/test_package.ambr
  tests/snowpark/test_build.py
  tests/snowpark/test_package.py
  tests/snowpark/test_snowpark_shared.py
  tests/test_utils.py
  tests/testing_utils/fixtures.py
  tests_integration/test_package.py
  tests_integration/test_snowpark.py
  tests_integration/testing_utils/snowpark_utils.py
Labels: 2.2.0

#959 improve snowpark integration tests
  tests_integration/test_data/projects/snowpark_version_check/.gitignore
  tests_integration/test_data/projects/snowpark_version_check/app/app.py
  tests_integration/test_data/projects/snowpark_version_check/requirements.txt
  tests_integration/test_data/projects/snowpark_version_check/snowflake.yml
  tests_integration/test_snowpark.py
Labels: 2.2.0

#942 Stage copy with directory structure
  RELEASE-NOTES.md
  src/snowflake/cli/api/output/types.py
  src/snowflake/cli/plugins/object/stage/commands.py
  src/snowflake/cli/plugins/object/stage/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/object/stage/__snapshots__/test_stage.ambr
  tests/object/stage/test_stage.py
  tests_integration/test_data/projects/stage_get_directory_structure/dir/script2.sql
  tests_integration/test_data/projects/stage_get_directory_structure/dir/subdir/script3.sql
  tests_integration/test_data/projects/stage_get_directory_structure/script1.sql
  tests_integration/test_stage.py
Labels: future-bcr

#963 Enable snowgit commands
  RELEASE-NOTES.md
  src/snowflake/cli/api/feature_flags.py
  tests/__snapshots__/test_help_messages.ambr
  tests_e2e/__snapshots__/test_installation.ambr
Labels: 2.2.0

#949 Added execute immediate command
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/object/stage/commands.py
  src/snowflake/cli/plugins/object/stage/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/__snapshots__/test_snow_connector.ambr
  tests/object/stage/__snapshots__/test_stage.ambr
  tests/object/stage/test_stage.py
  tests/streamlit/test_commands.py
  tests_integration/__snapshots__/test_stage.ambr
  tests_integration/test_data/projects/stage_execute/script1.sql
  tests_integration/test_data/projects/stage_execute/script2.sql
  tests_integration/test_data/projects/stage_execute/script3.sql
  tests_integration/test_data/projects/stage_execute/script_template.sql
  tests_integration/test_stage.py
Labels: 2.2.0

#916 Add is_default to connections list
  RELEASE-NOTES.md
  src/snowflake/cli/api/config.py
  src/snowflake/cli/app/snow_connector.py
  src/snowflake/cli/plugins/connection/commands.py
  tests/plugin/__snapshots__/test_override_by_external_plugins.ambr
  tests/plugin/test_broken_plugin.py
  tests/plugin/test_failing_plugin.py
  tests/plugin/test_override_by_external_plugins.py
  tests/test_connection.py
Labels: 2.2.0

#969 remove enable_snowgit feature flag
  src/snowflake/cli/api/feature_flags.py
  src/snowflake/cli/app/commands_registration/builtin_plugins.py
  tests/git/test_git_commands.py
  tests/test.toml
Labels: 2.2.0

#944 Fixed version parsing in AnacondaChannel
  .pre-commit-config.yaml
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/common.py
  src/snowflake/cli/plugins/snowpark/models.py
  src/snowflake/cli/plugins/snowpark/package/anaconda.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  tests/snowpark/__snapshots__/test_package.ambr
  tests/snowpark/test_anaconda.py
  tests/snowpark/test_common.py
  tests/snowpark/test_function.py
  tests/snowpark/test_package.py
  tests/test_data/test_data.py
  tests/test_utils.py
  tests_integration/test_package.py
  tests_integration/test_snowpark.py
Labels: 2.2.0

#980 Snow 1299785 move stage commands
  RELEASE-NOTES.md
  src/snowflake/cli/app/commands_registration/builtin_plugins.py
  src/snowflake/cli/plugins/git/commands.py
  src/snowflake/cli/plugins/git/manager.py
  src/snowflake/cli/plugins/nativeapp/manager.py
  src/snowflake/cli/plugins/nativeapp/run_processor.py
  src/snowflake/cli/plugins/object/__init__.py
  src/snowflake/cli/plugins/object/commands.py
  src/snowflake/cli/plugins/object/stage_deprecated/commands.py
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/package/manager.py
  src/snowflake/cli/plugins/stage/__init__.py
  src/snowflake/cli/plugins/stage/commands.py
  src/snowflake/cli/plugins/stage/diff.py
  src/snowflake/cli/plugins/stage/manager.py
  src/snowflake/cli/plugins/stage/plugin_spec.py
  src/snowflake/cli/plugins/streamlit/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/api/commands/__snapshots__/test_flags.ambr
  tests/api/commands/test_flags.py
  tests/git/test_git_commands.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/test_run_processor.py
  tests/object/test_stage.py
  tests/stage/__init__.py
  tests/stage/__snapshots__/test_stage.ambr
  tests/stage/test_diff.py
  tests/stage/test_stage.py
  tests_e2e/__snapshots__/test_installation.ambr
  tests_integration/test_git.py
  tests_integration/test_stage.py
Labels: 2.2.0, future-bcr

#984 Git copy should use recursive copy
  src/snowflake/cli/plugins/git/commands.py
  src/snowflake/cli/plugins/stage/commands.py
  tests/git/test_git_commands.py
Labels: 2.2.0

#991 [SNOW-1246906] Fetch available packages list from Snowflake instead of directly from Anaconda
  RELEASE-NOTES.md
  src/snowflake/cli/plugins/snowpark/commands.py
  src/snowflake/cli/plugins/snowpark/package/anaconda_packages.py
  src/snowflake/cli/plugins/snowpark/package/commands.py
  src/snowflake/cli/plugins/snowpark/package_utils.py
  tests/__snapshots__/test_help_messages.ambr
  tests/snowpark/__snapshots__/test_package.ambr
  tests/snowpark/mocks.py
  tests/snowpark/test_anaconda.py
  tests/snowpark/test_package.py
  tests/test_data/packages_available_in_snowflake_sql_result_rows.json
  tests/test_utils.py
  tests_integration/test_snowpark.py
Labels: 2.2.0

#995 Fixed snow object stage execute in release notes
  RELEASE-NOTES.md
Labels: 2.2.0
