Repository snowflakedb/snowflake-cli, pull requests merged in 2025-04, with the labels that each got.

#2170 Binary building fix
  scripts/packaging/build_isolated_binary_with_hatch.py
Labels: 3.6.0

#2182 Added missing feature flag check for auth
  src/snowflake/cli/_plugins/connection/commands.py
  tests/test_connection.py
Labels: 3.7.0

#2203 `Snow logs` fixes part 2: logs strike back
  src/snowflake/cli/_plugins/logs/commands.py
  src/snowflake/cli/_plugins/logs/manager.py
  src/snowflake/cli/_plugins/logs/utils.py
  tests/__snapshots__/test_help_messages.ambr
  tests/logs/__snapshots__/test_logs.ambr
  tests/logs/test_logs.py
  tests/logs/test_logs_utils.py
  tests_integration/test_data/projects/snowpark_v2/c.py
Labels: 3.7.0

#2206 run SPCS check on release PRs
  .github/workflows/test_integration_spcs.yaml
Labels: 3.7.0

#2202 SNOW-2040358 update all scripts if snow is not in the path
  RELEASE-NOTES.md
  scripts/packaging/macos/postinstall
Labels: enhancement, 3.7.0

#2220 Fix connection certificate issues
  RELEASE-NOTES.md
  pyproject.toml
  snyk/requirements.txt
Labels: 3.7.1

#2222 adding faster query to `snow spcs image-registry login`
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/spcs/image_registry/manager.py
  tests/spcs/test_registry.py
Labels: 3.7.1

#2237 Add support for queries, result and abort commands
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/sql/commands.py
  src/snowflake/cli/_plugins/sql/manager.py
  src/snowflake/cli/_plugins/sql/snowsql_commands.py
  src/snowflake/cli/_plugins/sql/statement_reader.py
  tests/sql/__snapshots__/test_repl.ambr
  tests/sql/__snapshots__/test_sql.ambr
  tests/sql/test_snowsql_commands.py
  tests/sql/test_statement_reader.py
  tests_integration/sql/__snapshots__/test_snowsql_commands.ambr
  tests_integration/sql/test_snowsql_commands.py
Labels: 3.8.0
