Repository snowflakedb/snowflake-cli, pull requests merged in 2025-05, with the labels that each got.

#2251 SNOW-2054743 Fix for error with `!=` in requirements
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/package/anaconda_packages.py
  tests/snowpark/test_anaconda.py
  tests/snowpark/test_package.py
  tests_integration/test_snowpark.py
Labels: 3.8.0

#2254 Snow 2089072 fix escaping identifiers for "use" commands
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/sf_sql_facade.py
  src/snowflake/cli/api/sql_execution.py
  tests/api/test_sql_execution.py
  tests/nativeapp/test_run_processor.py
  tests/nativeapp/test_sf_sql_facade.py
Labels: 3.8.0

#2179 Switch streamlit commands to use entities
  src/snowflake/cli/_plugins/streamlit/commands.py
  src/snowflake/cli/_plugins/streamlit/manager.py
  src/snowflake/cli/_plugins/streamlit/streamlit_entity.py
  src/snowflake/cli/api/entities/common.py
  src/snowflake/cli/api/entities/utils.py
  src/snowflake/cli/api/utils/path_utils.py
  src/snowflake/cli/api/utils/python_api_utils.py
  tests/app/test_telemetry.py
  tests/conftest.py
  tests/nativeapp/test_children.py
  tests/project/test_depends_on.py
  tests/streamlit/__snapshots__/test_actions.ambr
  tests/streamlit/__snapshots__/test_streamlit_commands.ambr
  tests/streamlit/__snapshots__/test_streamlit_entity.ambr
  tests/streamlit/streamlit_test_class.py
  tests/streamlit/test_artifacts.py
  tests/streamlit/test_commands.py
  tests/streamlit/test_streamlit_commands.py
  tests/streamlit/test_streamlit_entity.py
  tests/streamlit/test_streamlit_manager.py
  tests/test_data/projects/example_streamlit_multiple_v2/app_1.py
  tests/test_data/projects/example_streamlit_multiple_v2/app_2.py
  tests/test_data/projects/example_streamlit_multiple_v2/snowflake.yml
  tests/test_snow_connector.py
  tests/testing_utils/files_and_dirs.py
  tests_common/conftest.py
  tests_integration/test_data/projects/streamlit_v2/app_1.py
  tests_integration/test_data/projects/streamlit_v2/app_2.py
  tests_integration/test_data/projects/streamlit_v2/snowflake.yml
  tests_integration/test_snowpark.py
  tests_integration/test_snowpark_external_access.py
  tests_integration/test_streamlit.py
  tests_integration/test_streamlit_old.py
  tests_integration/testing_utils/snowpark_utils.py
  tests_integration/testing_utils/streamlit_utils.py
Labels: 3.8.0

#2266 Snow 2059612 single transaction support
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/sql/commands.py
  src/snowflake/cli/api/commands/flags.py
  src/snowflake/cli/api/sql_execution.py
  tests/__snapshots__/test_help_messages.ambr
  tests_integration/test_single_transaction_autocommit.py
Labels: 3.8.0

#2263 Move release channels feature flag to project-level
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/codegen/setup/native_app_setup_processor.py
  src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
  src/snowflake/cli/_plugins/nativeapp/feature_flags.py
  src/snowflake/cli/_plugins/snowpark/snowpark_entity.py
  src/snowflake/cli/api/feature_flags.py
  tests/nativeapp/test_application_package_entity.py
  tests/nativeapp/test_children.py
  tests/nativeapp/test_feature_flags.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/utils.py
  tests_integration/nativeapp/test_init_run.py
  tests_integration/nativeapp/test_publish.py
  tests_integration/nativeapp/test_release_channels.py
  tests_integration/nativeapp/test_release_directives.py
Labels: 3.8.0

#2272 fix error showing for --help messages
  pyproject.toml
  snyk/requirements.txt
Labels: 3.8.0, 3.7.2

#2278 SNOW-2100677: fix single transaction for stdin and files
  src/snowflake/cli/_plugins/sql/commands.py
  src/snowflake/cli/_plugins/sql/manager.py
  tests_integration/test_single_transaction_autocommit.py
Labels: 3.8.0

#2281 Fix deprecation message for enable_release_channels feature flag
  src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
  tests_integration/nativeapp/test_release_channels.py
Labels: 3.8.0

#2285 feat: [SNOW-2101016] check if project exists before adding new version
  src/snowflake/cli/_plugins/project/commands.py
  tests/dcm_project/test_commands.py
  tests_integration/test_dcm_project.py
  tests_integration/test_utils.py
Labels: 3.8.0

#2286 Snow 2101032 add date filters to query command
  src/snowflake/cli/_plugins/sql/snowsql_commands.py
  tests/sql/test_snowsql_commands.py
  tests_integration/conftest.py
  tests_integration/sql/__snapshots__/test_snowsql_commands.ambr
  tests_integration/sql/test_snowsql_commands.py
Labels: 3.8.0

#2284 Artifact repository - post bug-bash fixes
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/snowpark/common.py
  src/snowflake/cli/_plugins/snowpark/snowpark_entity.py
  src/snowflake/cli/_plugins/snowpark/snowpark_entity_model.py
  tests/snowpark/__snapshots__/test_snowpark_entity.ambr
  tests/snowpark/conftest.py
  tests/snowpark/test_snowpark_entity.py
  tests_integration/scripts/integration_account_setup.sql
  tests_integration/test_snowpark.py
Labels: 3.8.0

#2289 Snow-2011529 Fix for spcs metrics
  RELEASE-NOTES.md
  scripts/cleanup.py
  src/snowflake/cli/_plugins/spcs/common.py
  src/snowflake/cli/_plugins/spcs/services/commands.py
  src/snowflake/cli/_plugins/spcs/services/manager.py
  tests/spcs/__snapshots__/test_services.ambr
  tests/spcs/test_services.py
  tests_integration/scripts/integration_account_setup.sql
  tests_integration/spcs/spec/spec.yml
  tests_integration/spcs/test_services.py
  tests_integration/spcs/testing_utils/spcs_services_utils.py
Labels: 3.8.0

#2313 Snow 2106756 move upgrade warning to stderr
  RELEASE-NOTES.md
  src/snowflake/cli/_app/version_check.py
  tests/app/test_version_check.py
Labels: 3.8.1

#2311 fix cli for python 3.13
  .github/workflows/matrix.yaml
  RELEASE-NOTES.md
  pyproject.toml
  snyk/requirements.txt
  tests/nativeapp/codegen/test_sandbox.py
  tests_common/conftest.py
  tests_e2e/conftest.py
  tests_e2e/test_installation.py
  tests_e2e/test_nativeapp.py
  tests_integration/nativeapp/test_bundle.py
  tests_integration/test_git.py
Labels: 3.8.1

#2323 Snow 2113906 enable release channels should default to false
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/nativeapp/entities/application_package.py
  tests/nativeapp/test_application_package_entity.py
  tests/nativeapp/test_manager.py
  tests/nativeapp/utils.py
  tests_integration/nativeapp/test_release_channels.py
Labels: 3.8.2

#2318 Jw/snow 2111885 pupr readiness
  src/snowflake/cli/_app/commands_registration/builtin_plugins.py
  src/snowflake/cli/_plugins/dbt/__init__.py
  src/snowflake/cli/_plugins/dbt/commands.py
  src/snowflake/cli/_plugins/dbt/constants.py
  src/snowflake/cli/_plugins/dbt/manager.py
  src/snowflake/cli/_plugins/dbt/plugin_spec.py
  src/snowflake/cli/_plugins/snowpark/snowpark_entity.py
  src/snowflake/cli/api/commands/snow_typer.py
  src/snowflake/cli/api/constants.py
  src/snowflake/cli/api/feature_flags.py
  src/snowflake/cli/api/secure_path.py
  src/snowflake/cli/api/sql_execution.py
  tests/__snapshots__/test_help_messages.ambr
  tests/conftest.py
  tests/dbt/__init__.py
  tests/dbt/test_dbt_commands.py
  tests/dbt/test_manager.py
  tests_integration/__snapshots__/test_dbt.ambr
  tests_integration/conftest.py
  tests_integration/test_data/projects/dbt_project/dbt_project.yml
  tests_integration/test_data/projects/dbt_project/models/example/my_first_dbt_model.sql
  tests_integration/test_data/projects/dbt_project/models/example/my_second_dbt_model.sql
  tests_integration/test_data/projects/dbt_project/models/example/schema.yml
  tests_integration/test_data/projects/dbt_project/profiles.yml
  tests_integration/test_dbt.py
Labels: 3.9.0
