Repository snowflakedb/snowflake-cli, pull requests merged in 2025-06, with the labels that each got.

#2350 SNOW-208958: Update release notes
  RELEASE-NOTES.md
Labels: 3.9.1

#2435 feat: [SNOW-2157330] add --from option to project execute and dry-run…
  src/snowflake/cli/_plugins/project/commands.py
  src/snowflake/cli/_plugins/project/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/dcm_project/test_commands.py
  tests/dcm_project/test_manager.py
  tests_integration/test_dcm_project.py
Labels: AI

#2421 feat: [SNOW-2154833] implement project drop-version command
  src/snowflake/cli/_plugins/project/commands.py
  src/snowflake/cli/_plugins/project/manager.py
  tests/__snapshots__/test_help_messages.ambr
  tests/dcm_project/test_commands.py
  tests/dcm_project/test_manager.py
  tests_integration/test_dcm_project.py
Labels: AI

#2457 SNOW-1213448 add support stage-to-stage copy
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/stage/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/stage/__snapshots__/test_stage.ambr
  tests/stage/test_stage.py
  tests_integration/test_stage.py
Labels: AI

#2453 extra telemetry for gha
  .github/workflows/test_cli_action.yaml
  .github/workflows/test_cli_action_main_branch.yaml
  .github/workflows/test_cli_action_release_pr.yaml
  src/snowflake/cli/_app/telemetry.py
Labels: AI

#2467 mraba/setuptools: pin setuptools to 80.8 to disable deprecation warni…
  pyproject.toml
  snyk/requirements.txt
Labels: 3.10
