Repository snowflakedb/snowflake-cli, pull requests merged in 2025-03, with the labels that each got.

#2101 Added missing default for SPCS service and tests
  src/snowflake/cli/_plugins/spcs/compute_pool/commands.py
  src/snowflake/cli/_plugins/spcs/services/commands.py
  src/snowflake/cli/_plugins/spcs/services/service_entity_model.py
  tests/spcs/__snapshots__/test_compute_pool.ambr
  tests/spcs/__snapshots__/test_services.ambr
  tests/spcs/test_compute_pool.py
  tests/spcs/test_services.py
  tests/test_data/projects/spcs_compute_pool_only_required/snowflake.yml
  tests/test_data/projects/spcs_service_only_required/snowflake.yml
  tests/test_data/projects/spcs_service_only_required/spec.yml
Labels: 3.5.0

#2106 Make snowflake.yml required file for spcs deploy commands
  src/snowflake/cli/_plugins/notebook/commands.py
  src/snowflake/cli/_plugins/spcs/compute_pool/commands.py
  src/snowflake/cli/_plugins/spcs/image_repository/commands.py
  src/snowflake/cli/_plugins/spcs/services/commands.py
  tests/__snapshots__/test_help_messages.ambr
  tests/spcs/test_compute_pool.py
  tests/spcs/test_image_repository.py
  tests/spcs/test_services.py
Labels: 3.5.0

#2131 mraba/version-check-fix: add missing file_size_limit_mb for cache file
  RELEASE-NOTES.md
  src/snowflake/cli/_app/version_check.py
  tests/app/test_version_check.py
Labels: bug, 3.6.0

#2141 Snow 1999047 fix binaries visible as pypi in telemetry
  scripts/packaging/build_isolated_binary_with_hatch.py
  src/snowflake/cli/__about__.py
  src/snowflake/cli/_app/telemetry.py
Labels: 3.6.0

#2143 Fix typo in error message
  src/snowflake/cli/_app/snow_connector.py
Labels: 3.6.0

#2139 Added file execute log for stage and git
  RELEASE-NOTES.md
  src/snowflake/cli/_plugins/stage/manager.py
  tests/git/test_git_commands.py
  tests/stage/test_stage.py
Labels: 3.6.0

#2142 Auth rotate only overwrite connection
  src/snowflake/cli/_plugins/auth/keypair/commands.py
  src/snowflake/cli/_plugins/auth/keypair/manager.py
  tests/auth/__snapshots__/test_auth.ambr
  tests/auth/test_auth.py
Labels: 3.6.0

#2149 feat: [SNOW-2002186] save password based connection if subsequent key…
  src/snowflake/cli/_plugins/auth/keypair/manager.py
  src/snowflake/cli/_plugins/connection/commands.py
  src/snowflake/cli/api/exceptions.py
  tests/test_connection.py
Labels: 3.6.0

#2127 SNOW-1980772: command for checking variables
  src/snowflake/cli/_plugins/helpers/commands.py
  src/snowflake/cli/_plugins/helpers/snowsl_vars_reader.py
  tests/helpers/test_snowsql_env_vars.py
Labels: enhancement, 3.7.0

#2158 Snow 2011455 mac binary build fix
  scripts/packaging/build_darwin_package.sh
Labels: 3.6.0

#2157 Fix text positioning in Windows installer.
  scripts/packaging/win/snowflake_cli_exitdlg.wxs
Labels: 3.6.0

#2156 Updated docs for auth commands
  src/snowflake/cli/_plugins/auth/keypair/commands.py
  src/snowflake/cli/api/commands/flags.py
  tests/__snapshots__/test_docs_generation_output.ambr
  tests/__snapshots__/test_help_messages.ambr
  tests/api/commands/__snapshots__/test_snow_typer.ambr
  tests/sql/__snapshots__/test_sql.ambr
Labels: 3.6.0
